[project]
name = "heart-books"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipywidgets>=8.1.8",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "pip>=25.3",
]
